### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by dagnelies** [SPIRIT-21/swagger-doclet#4]
Sadly, it doesn't go very far...

javadoc: error - In doclet class com.spirit21.Doclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
java.lang.NullPointerException
	at com.spirit21.spring.parser.OperationParser.createOperations(OperationParser.java:49)
	at com.spirit21.spring.parser.PathParser.createOperation(PathParser.java:116)
	at com.spirit21.spring.parser.PathParser.createPath(PathParser.java:92)
	at com.spirit21.spring.parser.PathParser.setPath(PathParser.java:59)
	at com.spirit21.spring.parser.Parser.run(Parser.java:43)
	at com.spirit21.Doclet.runParser(Doclet.java:55)
	at com.spirit21.Doclet.start(Doclet.java:47)

**Comment by michaelweidmann** [comment]
Hello @dagnelies,

thanks for reporting.
The exception will be thrown when a method has no HTTP-annotation.
Can you plaese provide more information (for example a code snippet)?

**Comment by dagnelies** [comment]
I just let it run over my codebase. Since the error did not indicate anything more precise than this "NullPointerException" without more information, I do not know where or what in the code might have caused it. It's not a "hello world", it's actual code with many classes.

The only unusual thing that comes to my mind is an abstract class defining "request mappings" (i.e. `/foo`, `/bar`) without being a controller. The child classes of it are the controllers, with a class-level request mapping, resulting in `/child/foo`, `/child/bar` for example.

**Comment by michaelweidmann** [comment]
Thanks for your fast answer.
For the version 0.5 a better logging is planned. I hope to release the new version by the end of the week at the latest. After that you can try it again and hopefully we can fix your problem. 😃

**Comment by michaelweidmann** [comment]
Sorry, it takes a little bit longer. I have updated some dependency versions and some of them has changed a lot.

**Comment by mateobencek** [comment]
Has this been fixed? I am getting same error without much explanation
